version: '3'

services:
  api:
    build: ./api
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    environment:
      PG_HOST: postgres
      PG_USER: postgres
      PG_PASSWORD: password
      PG_DB: 'quiz_db'
    volumes:
      - ./api:/app
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: 'quiz_db'
    volumes:
      - pg_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'

volumes:
  pg_data: